#!/bin/bash
####################################################################
##                                                                ##
##  This script contains Git functions for BioLockJ + blj_support ##
##                                                                ##
####################################################################

# Git latest $BLJ + build BioLockJ.jar
function blj_git() {
	[ ! -d "$BLJ" ] && echo "Cannot build BLJ: directory not found: $BLJ_SUP" && return
	reset_git $BLJ
	$BLJ/script/blj_build build-jar
}

# Git latest $BLJ_SUP
function blj_sup_git() {
	[ ! -d "$BLJ_SUP" ] && echo "Cannot build BLJ_SUP: directory not found: $BLJ_SUP" && return
	reset_git $BLJ_SUP
}

# Reset git repo + set file permissions 770
# Param 1 Directory path of Git repo
function reset_git() {
	echo "Get latest code from GitHub repo: $1"
	cd $1
	git fetch
  	git checkout -q master
  	git reset -q --hard origin/master  
	chmod -R 770 $1
	echo "==========================================================================="
	echo "$1 Git pull SUCESSFULLY COMPLETED!"
	chmod -R 770 $1
	echo "$1 permissions set: 770"
	echo "==========================================================================="
	echo ""
}