#!/bin/bash
#########################################################################
##                                                                     ##
##  This script fetches the latest BioLockJ code from GitHub.          ##
##  Set $BLJ file permissions to 770, setgid bit assigns group owner   ##
##  Build the latest BioLockJ.jar file to $BLJ/dist                    ##
##                                                                     ##
##  This script sets all file permissions to 770 to ensure all users   ##
##  in our UNIX group have access.  Git tracks this as a change so     ##
##  may throw warnings about unstaged changes.  To avoid this we will  ##
##  stash changes before we pull and discard the stash.                ##
##                                                                     ##
#########################################################################

echo "Get latest code from BioLockJ GitHub"
cd $BLJ

git stash save -q --keep-index
git pull origin master
git stash drop -q

echo "Git pull successful!"

appDir=$(dirname $BLJ)
$appDir/blj_support/script/blj_deploy

echo "==========================================================================="
echo "BioLockJ Git pull + build SUCESSFULLY COMPLETED!!!"
echo "Deployment dir: $BLJ"
echo "==========================================================================="
echo ""
