#!/bin/bash
#########################################################################
##                                                                     ##
##  This script fetches the latest BioLockJ code from GitHub.          ##
##  Set $BLJ file permissions to 770, setgid bit assigns group owner   ##
##  Build the latest BioLockJ.jar file to $BLJ/dist                    ##
##                                                                     ##
##  This script sets all file permissions to 770 to ensure all users   ##
##  in our UNIX group have access.  Git tracks this as a change so     ##
##  may throw warnings about unstaged changes.  To avoid this we will  ##
##  stash changes before we pull and discard the stash.                ##
##                                                                     ##
#########################################################################

# Git latest $BLJ + build BioLockJ.jar
function blj_git() {
	[ !-d "$BLJ" ] && echo "Cannot build BLJ: directory not found: $BLJ_SUP" && return
	reset_git $BLJ
	$BLJ/script/blj_build build-jar
}

# Git latest $BLJ_SUP
function blj_sup_git() {
	[ !-d "$BLJ_SUP" ] && echo "Cannot build BLJ_SUP: directory not found: $BLJ_SUP" && return
	reset_git $BLJ_SUP
}

# Reset git repo + set file permissions 770
function reset_git() {
	echo "Get latest code from GitHub repo: $1"
	cd $1
	git fetch
  	git checkout master
  	git reset --hard origin/master  
	chmod -R 770 $1
	echo "==========================================================================="
	echo "$1 Git pull SUCESSFULLY COMPLETED!"
	chmod -R 770 $1
	echo "$1 permissions set: 770"
	echo "==========================================================================="
	echo ""
}