#!/bin/bash
#########################################################################
##                                                                     ##
##  This script fetches the latest blj_support code from GitHub.       ##
##  Set $BLJ_SUP 770 permissions & setuid/setgid bits to assign owner. ##
##                                                                     ##
##  This script sets all file permissions to 770 to ensure all users   ##
##  in our UNIX group have access.  Git tracks this as a change so     ##
##  may throw warnings about unstaged changes.  To avoid this we will  ##
##  stash changes before we pull and discard the stash.                ##
##                                                                     ##
#########################################################################

scriptDir="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
bljSupport="$( cd "$( dirname "$scriptDir" )" && pwd )"

echo "Pull latest blj_support code from GitHub"

cd $bljSupport
git stash save -q --keep-index
git pull origin master
git stash drop -q
echo "Git pull successful!"

$scriptDir/blj_sup_deploy

echo "==========================================================================="
echo "blj_support: Git pull + build SUCESSFULLY COMPLETED!!!"
echo "Deployment dir: $bljSupport"
echo "==========================================================================="
