#!/bin/bash
###########################################################################
##                                                                       ##
##  Build all Docker images                                              ##
##                                                                       ##
###########################################################################
. ${BLJ_SUP}/script/docker_functions

echo "Build new module images..."

docker build -t $DOCKER_HUB_USER/blj_basic${bljV} $DOCKER_FILE_PATH -f $DOCKER_FILE_PATH/blj_basic.Dockerfile
docker build -t $DOCKER_HUB_USER/blj_bash${bljV} $DOCKER_FILE_PATH -f $DOCKER_FILE_PATH/blj_bash.Dockerfile
docker build -t $DOCKER_HUB_USER/blj_basic_py2${bljV} $DOCKER_FILE_PATH -f $DOCKER_FILE_PATH/blj_basic_py2.Dockerfile
docker build -t $DOCKER_HUB_USER/blj_basic_java${bljV} $DOCKER_FILE_PATH -f $DOCKER_FILE_PATH/blj_basic_java.Dockerfile

$(buildBljCmd) -t $DOCKER_HUB_USER/java_module${bljV} $DOCKER_FILE_PATH -f $DOCKER_FILE_PATH/java_module.Dockerfile
$(buildBljDockCliCmd) -t $DOCKER_HUB_USER/biolockj_controller${bljV} $DOCKER_FILE_PATH -f $DOCKER_FILE_PATH/biolockj_controller.Dockerfile

docker build -t $DOCKER_HUB_USER/rdp_classifier${bljV} $DOCKER_FILE_PATH -f $DOCKER_FILE_PATH/rdp_classifier.Dockerfile
docker build -t $DOCKER_HUB_USER/qiime_classifier${bljV} $DOCKER_FILE_PATH -f $DOCKER_FILE_PATH/qiime_classifier.Dockerfile
docker build -t $DOCKER_HUB_USER/r_module${bljV} $DOCKER_FILE_PATH -f $DOCKER_FILE_PATH/r_module.Dockerfile

docker build -t $DOCKER_HUB_USER/metaphlan2_classifier_dbfree${bljV} $DOCKER_FILE_PATH -f $DOCKER_FILE_PATH/metaphlan2_classifier_dbfree.Dockerfile
docker build -t $DOCKER_HUB_USER/metaphlan2_classifier${bljV} $DOCKER_FILE_PATH -f $DOCKER_FILE_PATH/metaphlan2_classifier.Dockerfile
docker build -t $DOCKER_HUB_USER/knead_data_dbfree${bljV} $DOCKER_FILE_PATH -f $DOCKER_FILE_PATH/knead_data_dbfree.Dockerfile
docker build -t $DOCKER_HUB_USER/knead_data${bljV} $DOCKER_FILE_PATH -f $DOCKER_FILE_PATH/knead_data.Dockerfile
docker build -t $DOCKER_HUB_USER/humann2_classifier_dbfree${bljV} $DOCKER_FILE_PATH -f $DOCKER_FILE_PATH/humann2_classifier_dbfree.Dockerfile
docker build -t $DOCKER_HUB_USER/humann2_classifier${bljV} $DOCKER_FILE_PATH -f $DOCKER_FILE_PATH/humann2_classifier.Dockerfile

docker build -t $DOCKER_HUB_USER/kraken_classifier_dbfree${bljV} $DOCKER_FILE_PATH -f $DOCKER_FILE_PATH/kraken_classifier_dbfree.Dockerfile
docker build -t $DOCKER_HUB_USER/kraken_classifier${bljV} $DOCKER_FILE_PATH -f $DOCKER_FILE_PATH/kraken_classifier.Dockerfile
docker build -t $DOCKER_HUB_USER/kraken2_classifier_dbfree${bljV} $DOCKER_FILE_PATH -f $DOCKER_FILE_PATH/kraken2_classifier_dbfree.Dockerfile
docker build -t $DOCKER_HUB_USER/kraken2_classifier${bljV} $DOCKER_FILE_PATH -f $DOCKER_FILE_PATH/kraken2_classifier.Dockerfile

echo "Docker build complete!"
