#!/bin/bash
###########################################################################
##                                                                       ##
##  Push all Docker images to Docker hub                                 ##
##                                                                       ##
###########################################################################

echo "Push latest Docker images..."

docker push $DOCKER_HUB_USER/blj_basic${bljV}
docker push $DOCKER_HUB_USER/blj_bash${bljV}
docker push $DOCKER_HUB_USER/blj_basic_py2${bljV}
docker push $DOCKER_HUB_USER/blj_basic_java${bljV} 

docker push $DOCKER_HUB_USER/java_module${bljV}
docker push $DOCKER_HUB_USER/biolockj_controller${bljV}

docker push $DOCKER_HUB_USER/rdp_classifier${bljV}
docker push $DOCKER_HUB_USER/qiime_classifier${bljV}
docker push $DOCKER_HUB_USER/r_module${bljV}

docker push $DOCKER_HUB_USER/metaphlan2_classifier_dbfree${bljV}
docker push $DOCKER_HUB_USER/metaphlan2_classifier${bljV}
docker push $DOCKER_HUB_USER/knead_data_dbfree${bljV}
docker push $DOCKER_HUB_USER/knead_data${bljV}
docker push $DOCKER_HUB_USER/humann2_classifier_dbfree${bljV}
docker push $DOCKER_HUB_USER/humann2_classifier${bljV}

docker push $DOCKER_HUB_USER/kraken_classifier_dbfree${bljV}
docker push $DOCKER_HUB_USER/kraken2_classifier_dbfree${bljV}
docker push $DOCKER_HUB_USER/kraken_classifier${bljV}
docker push $DOCKER_HUB_USER/kraken2_classifier${bljV}

echo "Docker push complete!"
