#!/bin/bash
###########################################################################
##                                                                       ##
##  Pull all Docker hub images                                           ##
##                                                                       ##
###########################################################################

echo "Pull latest Docker images..."

docker pull $DOCKER_HUB_USER/blj_basic${bljV}
docker pull $DOCKER_HUB_USER/blj_bash${bljV}
docker pull $DOCKER_HUB_USER/blj_basic_py2${bljV}
docker pull $DOCKER_HUB_USER/blj_basic_java${bljV} 

docker pull $DOCKER_HUB_USER/java_module${bljV}
docker pull $DOCKER_HUB_USER/blj_manager${bljV}
docker pull $DOCKER_HUB_USER/aws_manager${bljV}
docker pull $DOCKER_HUB_USER/blj_webapp${bljV}

docker pull $DOCKER_HUB_USER/rdp_classifier${bljV}
docker pull $DOCKER_HUB_USER/qiime_classifier${bljV}
docker pull $DOCKER_HUB_USER/r_module${bljV}


docker pull $DOCKER_HUB_USER/metaphlan2_classifier_dbfree${bljV}
docker pull $DOCKER_HUB_USER/metaphlan2_classifier${bljV}
docker pull $DOCKER_HUB_USER/knead_data_dbfree${bljV}
docker pull $DOCKER_HUB_USER/knead_data${bljV}
docker pull $DOCKER_HUB_USER/humann2_classifier_dbfree${bljV}
docker pull $DOCKER_HUB_USER/humann2_classifier${bljV}

docker pull $DOCKER_HUB_USER/kraken_classifier_dbfree${bljV}
docker pull $DOCKER_HUB_USER/kraken2_classifier_dbfree${bljV}
docker pull $DOCKER_HUB_USER/kraken_classifier${bljV}
docker pull $DOCKER_HUB_USER/kraken2_classifier${bljV}

echo "Docker pull complete!"
