#!/bin/bash
###########################################################################
##                                                                       ##
##  Build all Docker images and push them to the Docker hub              ##
##                                                                       ##
###########################################################################

docker_build
clearDock
docker_push
