#!/bin/bash
###########################################################################
##                                                                       ##
##  Build all Docker images                                              ##
##                                                                       ##
###########################################################################
. $BLJ/script/blj_functions

echo "Build new module images..."

DOCK_BLJ="docker build --build-arg BLJ_DATE=$(date +%s) --build-arg VER=$(get_version)"
DOCK_BLJ_CLI="$DOCK_BLJ --build-arg DOCKER_CLIENT=$DOCKER_VER"

docker build -t $DOCKER_HUB_USER/blj_basic${bljV} $DOCKER_FILE_PATH -f $DOCKER_FILE_PATH/blj_basic.Dockerfile
docker build -t $DOCKER_HUB_USER/blj_bash${bljV} $DOCKER_FILE_PATH -f $DOCKER_FILE_PATH/blj_bash.Dockerfile
docker build -t $DOCKER_HUB_USER/blj_basic_py2${bljV} $DOCKER_FILE_PATH -f $DOCKER_FILE_PATH/blj_basic_py2.Dockerfile
docker build -t $DOCKER_HUB_USER/blj_basic_java${bljV} $DOCKER_FILE_PATH -f $DOCKER_FILE_PATH/blj_basic_java.Dockerfile

$DOCK_BLJ -t $DOCKER_HUB_USER/java_module${bljV} $DOCKER_FILE_PATH -f $DOCKER_FILE_PATH/java_module.Dockerfile
$DOCK_BLJ_CLI -t $DOCKER_HUB_USER/biolockj${bljV} $DOCKER_FILE_PATH -f $DOCKER_FILE_PATH/biolockj.Dockerfile
$DOCK_BLJ_CLI -t $DOCKER_HUB_USER/blj_webapp${bljV} $DOCKER_FILE_PATH -f $DOCKER_FILE_PATH/blj_webapp.Dockerfile

docker build -t $DOCKER_HUB_USER/rdp_classifier${bljV} $DOCKER_FILE_PATH -f $DOCKER_FILE_PATH/rdp_classifier.Dockerfile
docker build -t $DOCKER_HUB_USER/qiime_classifier${bljV} $DOCKER_FILE_PATH -f $DOCKER_FILE_PATH/qiime_classifier.Dockerfile
docker build -t $DOCKER_HUB_USER/r_module${bljV} $DOCKER_FILE_PATH -f $DOCKER_FILE_PATH/r_module.Dockerfile

docker build -t $DOCKER_HUB_USER/metaphlan2_classifier_dbfree${bljV} $DOCKER_FILE_PATH -f $DOCKER_FILE_PATH/metaphlan2_classifier_dbfree.Dockerfile
docker build -t $DOCKER_HUB_USER/metaphlan2_classifier${bljV} $DOCKER_FILE_PATH -f $DOCKER_FILE_PATH/metaphlan2_classifier.Dockerfile
docker build -t $DOCKER_HUB_USER/knead_data_dbfree${bljV} $DOCKER_FILE_PATH -f $DOCKER_FILE_PATH/knead_data_dbfree.Dockerfile
docker build -t $DOCKER_HUB_USER/knead_data${bljV} $DOCKER_FILE_PATH -f $DOCKER_FILE_PATH/knead_data.Dockerfile
docker build -t $DOCKER_HUB_USER/humann2_classifier_dbfree${bljV} $DOCKER_FILE_PATH -f $DOCKER_FILE_PATH/humann2_classifier_dbfree.Dockerfile
docker build -t $DOCKER_HUB_USER/humann2_classifier${bljV} $DOCKER_FILE_PATH -f $DOCKER_FILE_PATH/humann2_classifier.Dockerfile

docker build -t $DOCKER_HUB_USER/kraken_classifier_dbfree${bljV} $DOCKER_FILE_PATH -f $DOCKER_FILE_PATH/kraken_classifier_dbfree.Dockerfile
docker build -t $DOCKER_HUB_USER/kraken_classifier${bljV} $DOCKER_FILE_PATH -f $DOCKER_FILE_PATH/kraken_classifier.Dockerfile
docker build -t $DOCKER_HUB_USER/kraken2_classifier_dbfree${bljV} $DOCKER_FILE_PATH -f $DOCKER_FILE_PATH/kraken2_classifier_dbfree.Dockerfile
docker build -t $DOCKER_HUB_USER/kraken2_classifier${bljV} $DOCKER_FILE_PATH -f $DOCKER_FILE_PATH/kraken2_classifier.Dockerfile

echo "Docker build complete!"

# $DOCK_BLJ_CLI -t $DOCKER_HUB_USER/blj_manager${bljV} $DOCKER_FILE_PATH -f $DOCKER_FILE_PATH/blj_manager.Dockerfile
# $DOCK_BLJ -t $DOCKER_HUB_USER/aws_manager${bljV} $DOCKER_FILE_PATH -f $DOCKER_FILE_PATH/aws_manager.Dockerfile
